version: "3.8"
services:
  dayaway_db:
    image: postgres:13
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dayaway_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dayaway_password

  dayaway_backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - dayaway_db
    env_file:
      - ./backend/.env
    volumes:
      # Mount the entire backend directory from host to /app in container
      - ./backend:/app
      # Use a named volume for node_modules to prevent host's from overwriting container's
      - backend_node_modules:/app/node_modules
    command: npm run dev

  dayaway_frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - dayaway_backend
    # Assuming frontend also works out of /app and uses npm start/dev
    # Add env_file if needed for frontend
    volumes:
      # Mount the entire frontend directory from host to /app in container
      - ./frontend:/app
      # Use a named volume for node_modules
      - frontend_node_modules:/app/node_modules
    # Make sure the command is appropriate for frontend dev (e.g., npm start)
    # command: npm start # Or whatever your frontend uses

# Define ALL named volumes used above
volumes:
  dayaway_db_data:
  backend_node_modules: # Define the backend modules volume
  frontend_node_modules: # Define the frontend modules volume